# Generated by Django 5.2.3 on 2025-06-24 18:11

import django.db.models.deletion
import upload_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование группы')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload_files.productgroup', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Товарная группа',
                'verbose_name_plural': 'Товарные группы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('article', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Артикул')),
                ('trading_numbers', models.CharField(blank=True, max_length=255, verbose_name='Торговые номера')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('additional_name', models.TextField(blank=True, verbose_name='Дополнительное описание')),
                ('product_status', models.CharField(blank=True, max_length=50, verbose_name='Статус изделия')),
                ('specifications', models.TextField(blank=True, verbose_name='Характеристики')),
                ('product_group', models.ForeignKey(blank=True, default=upload_files.models.get_default_product_group, on_delete=django.db.models.deletion.SET_DEFAULT, to='upload_files.productgroup', verbose_name='Товарная группа')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
