# Generated by Django 5.2.3 on 2025-06-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cross_article',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кросс-артикул'),
        ),
        migrations.AddField(
            model_name='product',
            name='cross_brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кросс-бренд'),
        ),
    ]
