# Generated by Django 5.2.3 on 2025-06-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0002_product_cross_article_product_cross_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='trading_numbers',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Торговые номера'),
        ),
    ]
